const exerciseCategorizer= (exercisesArr) => {

    // OBJECT:
    // [
    //     { id: 12, name: 'ab coaster' },
    //     { id: 3, name: 'angled leg press (unloaded 136lbs)' },
    //     { id: 9, name: 'biceps curl' },
    //     { id: 8, name: 'converging chest press' },
    //     { id: 2, name: 'converging shoulder press' },
    //     { id: 6, name: 'diverging seated row' },
    //     { id: 4, name: 'inner thigh' },
    //     { id: 1, name: 'lateral pulldown' },
    //     { id: 7, name: 'lateral raise' },
    //     { id: 5, name: 'outer thigh' },
    //     { id: 13, name: 'rear delt' },
    //     { id: 11, name: 'rotary torso' },
    //     { id: 10, name: 'triceps extension' }
    //   ]

    const categories = {
        'upper-body': [
            'biceps curl',
            'triceps extension',
            'rear delt',
            'lateral pulldown',  
            'lat pulldown',
            'lateral pull down',
            'lat pull down',
            'lateral raise',
            'lat raise',
            'shoulder press',
            'converging shoulder press',
            'chest press',
            'converging chest press',
            'seated row',
            'diverging seated row',
            'Pull-Up',
            'Chin-Up',
            'Lat Pulldown',
            'Wide-Grip Lat Pulldown',
            'Close-Grip Lat Pulldown',
            'Barbell Row',
            'Bent-Over Row',
            'Dumbbell Row',
            'One-Arm Dumbbell Row',
            'T-Bar Row',
            'Seated Cable Row',
            'Machine Row',
            'Face Pull',
            'Reverse Fly',
            'Rear Delt Fly',
            'Superman Hold',
            'Overhead Press',
            'Military Press',
            'Shoulder Press',
            'Dumbbell Shoulder Press',
            'Arnold Press',
            'Lateral Raise',
            'Dumbbell Lateral Raise',
            'Cable Lateral Raise',
            'Front Raise',
            'Dumbbell Front Raise',
            'Cable Front Raise',
            'Rear Delt Raise',
            'Dumbbell Rear Delt Raise',
            'Upright Row',
            'Barbell Upright Row',
            'Dumbbell Upright Row',
            'Shrugs',
            'Dumbbell Shrugs',
            'Barbell Shrugs',
            'Barbell Curl',
            'Dumbbell Curl',
            'Bicep Curl',
            'EZ Bar Curl',
            'Hammer Curl',
            'Dumbbell Hammer Curl',
            'Cable Curl',
            'Preacher Curl',
            'Concentration Curl',
            'Zottman Curl',
            'Incline Dumbbell Curl',
            'Triceps Dip',
            'Bench Dip',
            'Close-Grip Bench Press',
            'Skull Crushers',
            'Lying Triceps Extension',
            'French Press',
            'Overhead Triceps Extension',
            'Dumbbell Triceps Extension',
            'Cable Triceps Extension',
            'Rope Triceps Pushdown',
            'Straight Bar Triceps Pushdown',
            'Straight Bar Triceps Push Down',
            'Reverse Grip Triceps Push Down',
            'Reverse Grip Triceps Pushdown',
            'Wrist Curl',
            'Dumbbell Wrist Curl',
            'Reverse Wrist Curl',
            'Farmer\'s Carry',
            'Plate Pinch Hold'
        ],
        'lower-body': [
            'angled leg press (unloaded 136lbs)',
            'angled leg press', 
            'leg press',
            'inner thigh',
            'outer thigh',
            'calf raise',
            'calf raises',
            'Squat',
            'Back Squat',
            'Barbell Squat',
            'Front Squat',
            'Goblet Squat',
            'Box Squat',
            'Hack Squat',
            'Sissy Squat',
            'Bulgarian Split Squat',
            'Pistol Squat',
            'Step-Up',
            'Dumbbell Step-Up',
            'Weighted Step-Up',
            'Leg Press',
            'Machine Leg Press',
            'Sled Leg Press',
            'Sled Push',
            'Lunge',
            'Forward Lunge',
            'Reverse Lunge',
            'Walking Lunge',
            'Dumbbell Lunge',
            'Barbell Lunge',
            'Split Squat',
            'Jump Squat',
            'Jumping Lunge',
            'Wall Sit',
            'Romanian Deadlift',
            'RDL',
            'Romanian Deadlift',
            'Dumbbell RDL',
            'Stiff-Leg Deadlift',
            'Good Morning',
            'Glute-Ham Raise',
            'Hamstring Curl',
            'Lying Hamstring Curl',
            'Seated Hamstring Curl',
            'Nordic Curl',
            'Single-Leg Romanian Deadlift',
            'Machine Hamstring Curl',
            'Hip Thrust',
            'Barbell Hip Thrust',
            'Dumbbell Hip Thrust',
            'Glute Bridge',
            'Weighted Glute Bridge',
            'Single-Leg Glute Bridge',
            'Cable Kickback',
            'Resistance Band Kickback',
            'Step-Up',
            'Reverse Hyperextension',
            'Kettlebell Swing',
            'Sled Push',
            'Calf Raise',
            'Standing Calf Raise',
            'Seated Calf Raise',
            'Donkey Calf Raise',
            'Single-Leg Calf Raise',
            'Smith Machine Calf Raise',
            'Jump Rope',
            'Farmer\'s Walk on Toes',
            'Sumo Deadlift',
            'Sumo Squat',
            'Cossack Squat',
            'Side Lunge',
            'Adductor Machine',
            'Abductor Machine',
            'Cable Lateral Leg Raise',
            'Clamshell',
            'Fire Hydrant',
            'Deadlift',
            'Conventional Deadlift',
            'Sumo Deadlift',
            'Trap Bar Deadlift',
            'Snatch-Grip Deadlift',
            'Olympic Lift Variations',
            'Clean and Jerk',
            'Power Clean',
            'Snatch',
            'Box Jump',
            'Broad Jump'
        ],
        'core': [
            'abs coaster',
            'ab coaster',
            'rotary torso',
            'dump sesh'
        ],
        'cardio': [
            'treadmill',
            'elliptical',
            'stairs',
            'stair machine'
        ],
    }

    var catKeys = Object.keys(categories);

    exercisesArr.forEach(exe => {
        exe.category = "other";
        for (let i = 0; i < catKeys.length; i++) {
            var key = catKeys[i];
            var list = categories[key];
            var name = exe.name || exe.exercise_name;
            if (list.includes(name.toLowerCase())) {
                exe.category = key;
            }
        }
    });

    return exercisesArr;
}

export default exerciseCategorizer;