/* eslint-disable @typescript-eslint/no-unused-vars */
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Roboto } from "next/font/google";
import ClientLoader from "./components/ClientLoader";
import Footer from "./components/Footer"; 
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import AuthProvider from "@/app/components/SessionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ["latin"], 
  weight: "400" 
});

const roboto = Roboto({ 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "700"],
  display: "swap" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased relative`}
      >
        <AuthProvider>
          <ClientLoader>{children}</ClientLoader>      
          <Footer></Footer>
        </AuthProvider>
      </body>
    </html>
  );
}
