
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Oswald, Roboto } from "next/font/google";
import ClientLoader from "./components/ClientLoader"; // Import ClientLoader
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ 
  subsets: ["latin"], 
  weight: "400" 
});

const oswald = Oswald({ 
  subsets: ["latin"], 
  weight: ["400", "700"],
  display: "swap" 
});

const roboto = Roboto({ 
  subsets: ["latin"], 
  weight: ["300", "400", "500", "700"],
  display: "swap" 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${roboto.className} antialiased`}
      >
        <ClientLoader>{children}</ClientLoader>      </body>
    </html>
  );
}
